alias composer="php /usr/local/bin/composer.phar"
alias phpmamp="/Applications/MAMP/bin/php/php7.1.1/bin/php"
alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'
alias sshaws="sh -i ./.ssh/AWSKey.pem ubuntu@54.169.70.70"
alias pg-start="launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
alias pg-stop="launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist"
alias start-mysql="sudo /usr/local/mysql/support-files/mysql.server start"
alias stop-mysql="sudo /usr/local/mysql/support-files/mysql.server stop"
alias python='python2'
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export GOPATH=/Users/ldhnam/go
export GOROOT=/usr/local/opt/go/libexec
export ANDROID_HOME=~/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
export PATH=~/.local/bin:$PATH
export JDK_17=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
export JDK_18=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
export PATH="$HOME/development/google-cloud-sdk/bin/:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH=$HOME/development/flutter/bin:$PATH
export GOBIN=$HOME/go/bin/
export PATH="$HOME/development/protoc/bin/:$PATH"
export PATH=/usr/local/scala/bin:$PATH
export PTOOLSPATH=/Users/ldhnam/development/phalcon-devtools/
export PATH=$PATH:/Users/ldhnam/development/phalcon-devtools
